name: github pages

on:
  push:
    branches:
      - web-blog
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false

jobs:
  upload_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: true #recursive  # Fetch the Docsy theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Site
        run: hugo
#      - run: hugo --minify 
      
      - name: Upload Data
        working-directory: ./algolia # equivalent of 'cd algolia'
        run : |
          npm install
          npm run data-upload -- -c \
            -f ../public/algolia.json \
            -a THM1C0CEUY \
            -k ${{ secrets.ALGORIA_ADMIN_API_KEY }} \
            -n blog.ahmadcloud.my.id

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHPAGES_TOKEN }}
          cname: web.ahmadcloud.my.id
